name: Update

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update_event

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Download Files
        run: python script/setup.py

      - name: Generate
        run: |
          python script/generate_characters.py
          python script/generate_boards.py
          python script/collections.py

      - name: Increse version
        run: python script/update.py

      - name: Get version
        id: version
        run: |
          echo version=v$(jq -r '.version' src/version.json) >> $GITHUB_OUTPUT
          echo changelog=$(curl -s "https://api.github.com/repos/kawinpattanai/33/releases/latest" | jq -r '.body' | tr '\n' '\r\n') >> $GITHUB_OUTPUT

      - name: Commit and push updated version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "characters, boards"
          git push

      - name: Convert & Zip
        run: |
          python script/convert.py
          python script/zip.py

      - name: Upload Data
        uses: softprops/action-gh-release@v1
        with:
          tag_name: '${{steps.version.outputs.version}}'
          body: '${{steps.version.outputs.changelog}}'
          files: SubwayBooster.zip

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
